version: '3.9'
services:
  frontend:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - backend-network

  backend:
    build:
      context: ./ORM_Projekt
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - database
    networks:
      - backend-network

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projekt_db
    ports:
      - 3306:3306
    volumes:
      - ./baza_projekt.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-network

networks:
  backend-network:
